### ISSUE TITLE
Improve error reporting during symbol table construction

### ISSUE THREAD

**Issue by Cirras** [integrated-application-development/sonar-delphi#129]
### Prerequisites

- [X] This improvement has not already been suggested.
- [X] This improvement would be generally useful, not specific to my code or setup.

### Engine area

Other

### Improvement description

When an error is encountered during symbol table construction, the cause is not always clear from the stack trace.

If there is a problematic file, that should be clearly communicated to the user.
At the moment, this doesn't happen consistently.

For example, here's a stack trace from a parsing error:

```
08:33:58.501 ERROR: Error during SonarScanner execution
java.lang.RuntimeException: line 139:30 no viable alternative at input '('
        at au.com.integradev.delphi.antlr.DelphiParser.reportError(DelphiParser.java:350)
        at au.com.integradev.delphi.antlr.DelphiParser.typeDecl(DelphiParser.java:6200)
        at au.com.integradev.delphi.antlr.DelphiParser.typeDeclaration(DelphiParser.java:4512)
        at au.com.integradev.delphi.antlr.DelphiParser.typeSection(DelphiParser.java:4171)
        at au.com.integradev.delphi.antlr.DelphiParser.interfaceDecl(DelphiParser.java:3379)
        at au.com.integradev.delphi.antlr.DelphiParser.unitInterface(DelphiParser.java:1688)
        at au.com.integradev.delphi.antlr.DelphiParser.unitWithoutImplementation(DelphiParser.java:1490)
        at au.com.integradev.delphi.antlr.DelphiParser.fileWithoutImplementation(DelphiParser.java:634)
        at au.com.integradev.delphi.file.DelphiFile.createAST(DelphiFile.java:171)
        at au.com.integradev.delphi.file.DelphiFile.setupFile(DelphiFile.java:129)
        at au.com.integradev.delphi.file.DelphiFile.from(DelphiFile.java:120)
        at au.com.integradev.delphi.symbol.SymbolTableBuilder.process(SymbolTableBuilder.java:282)
```

### Rationale

We want to encourage people to report issues, but a lack of information about the error can be a roadblock in cases like these.

See: https://github.com/integrated-application-development/sonar-delphi/issues/124#issuecomment-1846895757

**Comment by Cirras** [comment]
Looks like we've already made a very good effort to do just this, but an overly-general `RuntimeException` being raised by `DelphiParser` is causing some headaches.

It skips past the try/catch in `DelphiFile::setupFile`...
```java
  static void setupFile(DefaultDelphiFile delphiFile, File sourceFile, DelphiFileConfig config) {
    try {
      // ...
    } catch (IOException | RecognitionException | EmptyDelphiFileException e) { // RuntimeException will not be wrapped here
      throw new DelphiFileConstructionException(e);
    }
  }
```

and then in `SymbolTableBuilder::process`, it's not a `DelphiFileConstructionException` as expected...
```java
  private void process(UnitData unit, ResolutionLevel resolutionLevel) {
    if (unit.resolved.ordinal() >= resolutionLevel.ordinal()) {
      return;
    }

    try {
      ++nestingLevel;
      // ...
    } catch (DelphiFileConstructionException e) { // RuntimeException is not caught here...
      String error = String.format("Error while processing %s", unit.unitFile.toAbsolutePath());
      LOG.error(error, e);
    } finally {
      --nestingLevel;
    }
```

So the solution will actually just be to throw a more specific exception type from the generated `DelphiParser`.
I'll also make sure that we're properly handling exceptions from `DelphiLexer`.
