### ISSUE TITLE
Parsing failures on named OLE automation arguments

### ISSUE THREAD

**Issue by CoppensBart** [integrated-application-development/sonar-delphi#204]
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.3.0

### SonarQube version

Community Edition - Version 10.4.1 (build 88267)

### Issue description

When scanning my project I get the following error message:

`
ERROR: Error while analyzing C:\Projects\SonarDemo\Unit1.pas
au.com.integradev.delphi.file.DelphiFile$DelphiFileConstructionException: Failed to construct DelphiFile (line 31:0 missing FORWARD at 'var')
        at au.com.integradev.delphi.file.DelphiFile.setupFile(DelphiFile.java:159)
        at au.com.integradev.delphi.file.DelphiFile$DelphiInputFile.from(DelphiFile.java:77)
        at au.com.integradev.delphi.DelphiSensor.executeOnFiles(DelphiSensor.java:143)
        at au.com.integradev.delphi.DelphiSensor.execute(DelphiSensor.java:83)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
        at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:82)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:223)
        at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:202)
        at org.sonar.scanner.scan.SpringProjectScanContainer.scan(SpringProjectScanContainer.java:197)
        at org.sonar.scanner.scan.SpringProjectScanContainer.scanRecursively(SpringProjectScanContainer.java:193)
        at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:166)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:223)
        at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:202)
        at org.sonar.scanner.bootstrap.SpringScannerContainer.doAfterStart(SpringScannerContainer.java:351)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:223)
        at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:202)
        at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:138)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:223)
        at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:202)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:71)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:65)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at jdk.proxy1/jdk.proxy1.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:126)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
        at org.sonarsource.scanner.cli.Main.main(Main.java:62)
Caused by: au.com.integradev.delphi.antlr.DelphiParser$ParserException: line 31:0 missing FORWARD at 'var'
        at au.com.integradev.delphi.antlr.DelphiParser.reportError(DelphiParser.java:351)
        at org.antlr.runtime.BaseRecognizer.recoverFromMismatchedToken(BaseRecognizer.java:613)
        at org.antlr.runtime.BaseRecognizer.match(BaseRecognizer.java:115)
        at au.com.integradev.delphi.antlr.DelphiParser.forwardDirectiveSection(DelphiParser.java:31497)
        at au.com.integradev.delphi.antlr.DelphiParser.forwardRoutineHeading(DelphiParser.java:16612)
        at au.com.integradev.delphi.antlr.DelphiParser.forwardRoutine(DelphiParser.java:15794)
        at au.com.integradev.delphi.antlr.DelphiParser.routineImplementation(DelphiParser.java:15560)
        at au.com.integradev.delphi.antlr.DelphiParser.declSection(DelphiParser.java:3369)
        at au.com.integradev.delphi.antlr.DelphiParser.unitImplementation(DelphiParser.java:1923)
        at au.com.integradev.delphi.antlr.DelphiParser.unit(DelphiParser.java:1539)
        at au.com.integradev.delphi.antlr.DelphiParser.file(DelphiParser.java:488)
        at au.com.integradev.delphi.file.DelphiFile.createAST(DelphiFile.java:194)
        at au.com.integradev.delphi.file.DelphiFile.setupFile(DelphiFile.java:149)
        ... 36 common frames omitted
Caused by: org.antlr.runtime.MissingTokenException: null
        at org.antlr.runtime.BaseRecognizer.recoverFromMismatchedToken(BaseRecognizer.java:612)
        ... 47 common frames omitted
`

### Steps to reproduce

Run a scan against the attached demo project

### Minimal Delphi code exhibiting the issue

Minimal Delphi project to reproduce the issue

[SonarDemo.zip](https://github.com/integrated-application-development/sonar-delphi/files/14612236/SonarDemo.zip)

**Comment by Cirras** [comment]
Hi Bart,

Thanks for this useful bug report.

TIL that OLE automation calls can have named arguments!
```pas
procedure Test;
var
  Foo: OleVariant;
begin
  Foo := CreateOleObject('Foo');
  Foo.Bar(Baz := 'Flarp');
end;
```

We'll add support for this syntax.

**Comment by CoppensBart** [comment]
@Cirras  , thank you for the quick reply
