### ISSUE TITLE
Parsing errors should be better handled

### ISSUE THREAD

**Issue by EduardoVaz06** [integrated-application-development/sonar-delphi#301]
### Prerequisites

- [X] This question has not already been answered.
- [X] This question is about SonarDelphi, not SonarQube or Delphi.

### Inquiry

Hello!

In my company, we have hundreds of Delphi projects wich we run SonarQube analysis (with Sonar Delphi). In the analysis there are a bunch of parsing errors, mostly related to encoding problems. 

Checking some other language plugins, I noticed that almost all of them have a "Parsing error" rule , wich raises an issue when a file fails to be parsed, rather then raise an error log on SonarScanner execution.

![image](https://github.com/user-attachments/assets/789b3784-2910-4ddc-a4e1-5bf449c95506)

![image](https://github.com/user-attachments/assets/b4c11143-7f72-4b69-b688-c2afee7633e0)

So, I wanted to start the discussion asking if an optional rule with this objective makes sense, raising issues when a file fails to be parsed if the rule is active, or keep raising an error log if it's not.

**Comment by fourls** [comment]
Hi @EduardoVaz06, apologies for the delay! We've been hotly debating this internally, no consensus yet.

Some pros of having a parse error rule:

* Consistent with official SonarSource plugins
* Gives a much more obvious indicator of an error, reducing the chance that a problem flies under the radar
    * Much more accessible to end users
* Ensures that files that fail to parse don't give a false impression of being a file with 0 issues

Some cons of having a parse error rule:

* Parse errors are categorised wrongly as code quality issues
    * A great example of how this could be frustrating: a parse error comes up as an issue, it fails the quality gate, so CI/CD freezes while the "issue" is resolved - but how do you resolve the issue? 
    * Parse errors are only the code's fault if it doesn't compile - because we have had to reverse-engineer the grammar for Delphi, it's often the case that the parse errors are on valid (but obscure) Delphi constructs
* Not as much information can be conveyed through an issue title - we would still have to raise an error log if we want the same amount of information as we have now

I think this question comes down to ideology vs practicality. On one hand, parsing errors aren't issues and we shouldn't treat them that way. On the other hand, this is the most visible option the Sonar ecosystem gives us to report errors- and is indeed what SonarSource does officially.

Interested to hear thoughts from others as well.

**Comment by fourls** [comment]
> In the analysis there are a bunch of parsing errors, mostly related to encoding problems.

Also worth mentioning that SonarDelphi is fully equipped to deal with different text encodings. Setting the `sonar.sourceEncoding` property to the [name or alias](https://www.iana.org/assignments/character-sets/character-sets.xhtml) for your encoding should allow the files to be read properly. If this doesn't work, there might be another bug at play.

**Comment by LinriAB** [comment]
I'm wondering if my problems might relate to the same thing, that is encoding. I've tried different encodings, but that doesn't seem to change anything. Some examples of DelphiParser errors I get are included below. Stack trace seems to be the same and I can include more of it if needed. Or, if this is more likely a bug, I'd be happy to report it. As I'm new to this plugin though, I thought it best to ask first, and I tend to lean towards some encoding problem. Our source files are ANSI, I've tried iso-8859-1 and windows-1252 (apart from utf-8).

09:17:06.430 ERROR Error while processing C:\gitlab-runner\builds\sCyaQG4y\0\secura\administrator\Lib\Secura Lib\SecuraTable.pas
au.com.integradev.delphi.file.DelphiFile$DelphiFileConstructionException: Failed to construct DelphiFile (line 5765:35 mismatched input '>=' expecting GREATER_THAN)
	at au.com.integradev.delphi.file.DelphiFile.setupFile(DelphiFile.java:161)
	at au.com.integradev.delphi.file.DelphiFile.from(DelphiFile.java:136)
	at au.com.integradev.delphi.symbol.SymbolTableBuilder.process(SymbolTableBuilder.java:288)
	at au.com.integradev.delphi.symbol.SymbolTableBuilder.createImportDeclaration(SymbolTableBuilder.java:219)

09:17:07.478 ERROR Error while processing C:\gitlab-runner\builds\sCyaQG4y\0\secura\administrator\Lib\Secura Lib\pnglang2.pas
au.com.integradev.delphi.file.DelphiFile$DelphiFileConstructionException: Failed to construct DelphiFile (line 304:0 mismatched character '<EOF>' expecting ''')

09:17:32.233 ERROR Error while processing C:\gitlab-runner\builds\sCyaQG4y\0\secura\administrator\Lib\Secura Lib\SecuraGrid.pas
au.com.integradev.delphi.file.DelphiFile$DelphiFileConstructionException: Failed to construct DelphiFile (line 223:21 no viable alternative at input '(')

**Comment by simonegirlanda** [comment]
@LinriAB could this be related to #318?
