### ISSUE TITLE
parsing error on method parameter declaration "cAdditionalSQL: IDictionary<string, string>=nil"

### ISSUE THREAD

**Issue by simonegirlanda** [integrated-application-development/sonar-delphi#318]
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.11.0

### SonarQube version

10.7

### Issue description

We had this error during parsing:

> ERROR Error while analyzing D:\test\ant\test.pas au.com.integradev.delphi.file.DelphiFile$DelphiFileConstructionException: Failed to construct DelphiFile (line 7:21 no viable alternative at input '(')

adding spaces before the = sign  in the parameter declaration will solve the problem

### Steps to reproduce

try analyze the following code.
add spaces before and after the = sign (in the class Public methods declaration) to remove the error

### Case 1

```
unit test;
Interface
Type
  TAnagrafica = Class(TObject)
   Public
    procedure GetSlaveItemsBad(cAdditionalSQL: IDictionary<string, string>=nil); // bad declaration --> generate parsing error
    procedure GetSlaveItemsGood(cAdditionalSQL: IDictionary<string, string> = nil); // good declaration --> no error  
  End;
Implementation
End.
```

### another code example
In this case a 'missing FORWARD' message error is produced

```
unit testassignment;
interface
type
 myclass = Class(Tobject)
   Public
	Procedure myMethod;
 End;
 
Implementation


 Procedure myClass.myMethod;
 Var
    B : Boolean;
 const
  aEntityTableNames: tArray<string>=[EntityField_TableName,
                                    EntityAction_TableName,
                                    Linguaggio_TableName,
                                    Postazione_TableName,
                                    Config_EntityName,
                                    Utente_EntityName,
                                    Gruppo_TableName];	

Begin
End;
  
 end.
```

**Comment by zaneduffield** [comment]
My guess is that the `>=` is being tokenised as a greater-than-or-equal token, which explains why adding the spaces helps.

This is yet another argument in favour of #261 (and against tokenising before parsing).

**Comment by Cirras** [comment]
Agreed with @zaneduffield.
This is blocked by #261.

**Comment by simonegirlanda** [comment]
Added code example from #321

**Comment by LinriAB** [comment]
Thanks @simonegirlanda, this topic seems a much better fit for the problems I'm having. 

A few additional examples for this issue:

09:17:06.430 ERROR Error while processing C:\gitlab-runner\builds\sCyaQG4y\0\secura\administrator\Lib\Secura Lib\SecuraTable.pas
au.com.integradev.delphi.file.DelphiFile$DelphiFileConstructionException: Failed to construct DelphiFile (line 5765:35 mismatched input '>=' expecting GREATER_THAN)
at au.com.integradev.delphi.file.DelphiFile.setupFile(DelphiFile.java:161)
at au.com.integradev.delphi.file.DelphiFile.from(DelphiFile.java:136)
at au.com.integradev.delphi.symbol.SymbolTableBuilder.process(SymbolTableBuilder.java:288)
at au.com.integradev.delphi.symbol.SymbolTableBuilder.createImportDeclaration(SymbolTableBuilder.java:219)

09:17:07.478 ERROR Error while processing C:\gitlab-runner\builds\sCyaQG4y\0\secura\administrator\Lib\Secura Lib\pnglang2.pas
au.com.integradev.delphi.file.DelphiFile$DelphiFileConstructionException: Failed to construct DelphiFile (line 304:0 mismatched character '' expecting ''')

09:17:32.233 ERROR Error while processing C:\gitlab-runner\builds\sCyaQG4y\0\secura\administrator\Lib\Secura Lib\SecuraGrid.pas
au.com.integradev.delphi.file.DelphiFile$DelphiFileConstructionException: Failed to construct DelphiFile (line 223:21 no viable alternative at input '(')

**Comment by Cirras** [comment]
Hi @LinriAB,

Your first case is almost certainly an instance of this issue, but I'm not so sure about cases 2 and 3.

Can you isolate the problem a bit further, maybe share some snippets of code that reproduce those other errors?
That would help us determine if the additional cases need separate issues or not.
